# Generated by Django 4.1.5 on 2023-01-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_posts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posto',
        ),
    ]
